export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const LOGIN_USER = 'LOGIN_USER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT = 'LOGOUT';

export const FETCH_CATALOG_START = 'FETCH_CATALOG_START';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';

export const FETCH_INVENTORY_START = 'FETCH_INVENTORY_START';
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
export const FETCH_INVENTORY_FAILURE = 'FETCH_INVENTORY_FAILURE';
export const ADJUST_INVENTORY = 'ADJUST_INVENTORY';

export const PROCESS_PAYMENT_START = 'PROCESS_PAYMENT_START';
export const PROCESS_PAYMENT_SUCCESS = 'PROCESS_PAYMENT_SUCCESS';
export const PROCESS_PAYMENT_FAILURE = 'PROCESS_PAYMENT_FAILURE';

export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE';

export const CREATE_BOOKING_START = 'CREATE_BOOKING_START';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';

export const FETCH_LOYALTY_ACCOUNTS_START = 'FETCH_LOYALTY_ACCOUNTS_START';
export const FETCH_LOYALTY_ACCOUNTS_SUCCESS = 'FETCH_LOYALTY_ACCOUNTS_SUCCESS';
export const FETCH_LOYALTY_ACCOUNTS_FAILURE = 'FETCH_LOYALTY_ACCOUNTS_FAILURE';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const FETCH_CONTENT_START = 'FETCH_CONTENT_START';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAILURE = 'FETCH_CONTENT_FAILURE';
export const UPDATE_CONTENT_START = 'UPDATE_CONTENT_START';
export const UPDATE_CONTENT_SUCCESS = 'UPDATE_CONTENT_SUCCESS';
export const UPDATE_CONTENT_FAILURE = 'UPDATE_CONTENT_FAILURE';

export const FETCH_ORDER_DETAILS_START = 'FETCH_ORDER_DETAILS_START';
export const FETCH_ORDER_DETAILS_SUCCESS = 'FETCH_ORDER_DETAILS_SUCCESS';
export const FETCH_ORDER_DETAILS_FAILURE = 'FETCH_ORDER_DETAILS_FAILURE';
export const CONFIRM_ORDER_START = 'CONFIRM_ORDER_START';
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS';
export const CONFIRM_ORDER_FAILURE = 'CONFIRM_ORDER_FAILURE';

export const FETCH_EVENTS_START = 'FETCH_EVENTS_START';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const UPDATE_CART_SUMMARY_START = 'UPDATE_CART_SUMMARY_START';
export const UPDATE_CART_SUMMARY_SUCCESS = 'UPDATE_CART_SUMMARY_SUCCESS';
export const UPDATE_CART_SUMMARY_FAILURE = 'UPDATE_CART_SUMMARY_FAILURE';
export const FETCH_CART_SUMMARY_START = 'FETCH_CART_SUMMARY_START';
export const FETCH_CART_SUMMARY_SUCCESS = 'FETCH_CART_SUMMARY_SUCCESS';
export const FETCH_CART_SUMMARY_FAILURE = 'FETCH_CART_SUMMARY_FAILURE';

export const FETCH_PAYMENTS_HISTORY_START = 'FETCH_PAYMENTS_HISTORY_START';
export const FETCH_PAYMENTS_HISTORY_SUCCESS = 'FETCH_PAYMENTS_HISTORY_SUCCESS';
export const FETCH_PAYMENTS_HISTORY_FAILURE = 'FETCH_PAYMENTS_HISTORY_FAILURE';

export const REFUND_PAYMENT_START = 'REFUND_PAYMENT_START';
export const REFUND_PAYMENT_SUCCESS = 'REFUND_PAYMENT_SUCCESS';
export const REFUND_PAYMENT_FAILURE = 'REFUND_PAYMENT_FAILURE';

export const FETCH_PAYMENT_DETAILS_START = 'FETCH_PAYMENT_DETAILS_START';
export const FETCH_PAYMENT_DETAILS_SUCCESS = 'FETCH_PAYMENT_DETAILS_SUCCESS';
export const FETCH_PAYMENT_DETAILS_FAILURE = 'FETCH_PAYMENT_DETAILS_FAILURE';

// action types
export const FETCH_CUSTOMER_DETAILS_REQUEST = 'FETCH_CUSTOMER_DETAILS_REQUEST';
export const FETCH_CUSTOMER_DETAILS_SUCCESS = 'FETCH_CUSTOMER_DETAILS_SUCCESS';
export const FETCH_CUSTOMER_DETAILS_FAILURE = 'FETCH_CUSTOMER_DETAILS_FAILURE';

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';

export const CREATE_CATALOG_START = 'CREATE_CATALOG_START';
export const CREATE_CATALOG_SUCCESS = 'CREATE_CATALOG_SUCCESS';
export const CREATE_CATALOG_FAILURE = 'CREATE_CATALOG_FAILURE';


export const DELETE_CATALOG_ITEM_START = 'DELETE_CATALOG_ITEM_START';
export const DELETE_CATALOG_ITEM_SUCCESS = 'DELETE_CATALOG_ITEM_SUCCESS';
export const DELETE_CATALOG_ITEM_FAILURE = 'DELETE_CATALOG_ITEM_FAILURE';

export const CATALOG_SEARCH_START = 'CATALOG_SEARCH_START';
export const CATALOG_SEARCH_SUCCESS = 'CATALOG_SEARCH_SUCCESS';
export const CATALOG_SEARCH_FAILURE = 'CATALOG_SEARCH_FAILURE';

export const FETCH_CATALOG_ITEM_START = 'FETCH_CATALOG_ITEM_START';
export const FETCH_CATALOG_ITEM_SUCCESS = 'FETCH_CATALOG_ITEM_SUCCESS';
export const FETCH_CATALOG_ITEM_FAILURE = 'FETCH_CATALOG_ITEM_FAILURE';

export const UPDATE_BOOKING_START = 'UPDATE_BOOKING_START';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';

export const CANCEL_BOOKING_START = 'CANCEL_BOOKING_START';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAILURE = 'CANCEL_BOOKING_FAILURE';

export const RETRIEVE_BOOKING_START = 'RETRIEVE_BOOKING_START';
export const RETRIEVE_BOOKING_SUCCESS = 'RETRIEVE_BOOKING_SUCCESS';
export const RETRIEVE_BOOKING_FAILURE = 'RETRIEVE_BOOKING_FAILURE';

export const FETCH_BOOKINGS_START = 'FETCH_BOOKINGS_START';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE';

export const SEARCH_AVAILABILITY_START = 'SEARCH_AVAILABILITY_START';
export const SEARCH_AVAILABILITY_SUCCESS = 'SEARCH_AVAILABILITY_SUCCESS';
export const SEARCH_AVAILABILITY_FAILURE = 'SEARCH_AVAILABILITY_FAILURE';

export const BULK_RETRIEVE_BOOKINGS_START = 'BULK_RETRIEVE_BOOKINGS_START';
export const BULK_RETRIEVE_BOOKINGS_SUCCESS = 'BULK_RETRIEVE_BOOKINGS_SUCCESS';
export const BULK_RETRIEVE_BOOKINGS_FAILURE = 'BULK_RETRIEVE_BOOKINGS_FAILURE';

export const BATCH_RETRIEVE_INVENTORY_COUNTS_START = 'BATCH_RETRIEVE_INVENTORY_COUNTS_START';
export const BATCH_RETRIEVE_INVENTORY_COUNTS_SUCCESS = 'BATCH_RETRIEVE_INVENTORY_COUNTS_SUCCESS';
export const BATCH_RETRIEVE_INVENTORY_COUNTS_FAILURE = 'BATCH_RETRIEVE_INVENTORY_COUNTS_FAILURE';

export const BATCH_ADJUST_INVENTORY_START = 'BATCH_ADJUST_INVENTORY_START';
export const BATCH_ADJUST_INVENTORY_SUCCESS = 'BATCH_ADJUST_INVENTORY_SUCCESS';
export const BATCH_ADJUST_INVENTORY_FAILURE = 'BATCH_ADJUST_INVENTORY_FAILURE';

export const CREATE_LOYALTY_ACCOUNT_START = 'CREATE_LOYALTY_ACCOUNT_START';
export const CREATE_LOYALTY_ACCOUNT_SUCCESS = 'CREATE_LOYALTY_ACCOUNT_SUCCESS';
export const CREATE_LOYALTY_ACCOUNT_FAILURE = 'CREATE_LOYALTY_ACCOUNT_FAILURE';

export const SEARCH_LOYALTY_ACCOUNTS_START = 'SEARCH_LOYALTY_ACCOUNTS_START';
export const SEARCH_LOYALTY_ACCOUNTS_SUCCESS = 'SEARCH_LOYALTY_ACCOUNTS_SUCCESS';
export const SEARCH_LOYALTY_ACCOUNTS_FAILURE = 'SEARCH_LOYALTY_ACCOUNTS_FAILURE';

export const RETRIEVE_LOYALTY_ACCOUNT_START = 'RETRIEVE_LOYALTY_ACCOUNT_START';
export const RETRIEVE_LOYALTY_ACCOUNT_SUCCESS = 'RETRIEVE_LOYALTY_ACCOUNT_SUCCESS';
export const RETRIEVE_LOYALTY_ACCOUNT_FAILURE = 'RETRIEVE_LOYALTY_ACCOUNT_FAILURE';

export const ACCUMULATE_LOYALTY_POINTS_START = 'ACCUMULATE_LOYALTY_POINTS_START';
export const ACCUMULATE_LOYALTY_POINTS_SUCCESS = 'ACCUMULATE_LOYALTY_POINTS_SUCCESS';
export const ACCUMULATE_LOYALTY_POINTS_FAILURE = 'ACCUMULATE_LOYALTY_POINTS_FAILURE';

export const ADJUST_LOYALTY_POINTS_START = 'ADJUST_LOYALTY_POINTS_START';
export const ADJUST_LOYALTY_POINTS_SUCCESS = 'ADJUST_LOYALTY_POINTS_SUCCESS';
export const ADJUST_LOYALTY_POINTS_FAILURE = 'ADJUST_LOYALTY_POINTS_FAILURE';

export const CREATE_CATALOG_IMAGE_REQUEST = 'CREATE_CATALOG_IMAGE_REQUEST';
export const CREATE_CATALOG_IMAGE_SUCCESS = 'CREATE_CATALOG_IMAGE_SUCCESS';
export const CREATE_CATALOG_IMAGE_FAILURE = 'CREATE_CATALOG_IMAGE_FAILURE';

export const UPDATE_CATALOG_IMAGE_REQUEST = 'UPDATE_CATALOG_IMAGE_REQUEST';
export const UPDATE_CATALOG_IMAGE_SUCCESS = 'UPDATE_CATALOG_IMAGE_SUCCESS';
export const UPDATE_CATALOG_IMAGE_FAILURE = 'UPDATE_CATALOG_IMAGE_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const CLEAR_BOOKING_ERROR = 'CLEAR_BOOKING_ERROR';